[lock]
background = "#FAFBFC"
background-alpha = 1.0
text = "#283545"
placeholder = "#62748A"
text-error = "#283545"
border = "#A8B3C1"
border-active = "#354B67"
border-error = "#283545"
border-alpha = 1.0
selection = "#354B67"
selection-alpha = 0.15
